<template><div><h1 id="_23-08-15" tabindex="-1"><a class="header-anchor" href="#_23-08-15" aria-hidden="true">#</a> 23.08.15</h1>
<h2 id="南京中盈优创" tabindex="-1"><a class="header-anchor" href="#南京中盈优创" aria-hidden="true">#</a> 南京中盈优创</h2>
<ol>
<li>自我介绍</li>
<li>上段实习干啥了</li>
<li>mysql数据类型</li>
<li>mysql常用语句、函数、索引失效、查询用时很长优化、表连接查询有哪些，区别呢</li>
<li>mybatisplus多表查询api</li>
<li>mybatis xml文件标签</li>
<li>Java数据类型及包装类</li>
<li>重写和重载区别</li>
<li>equals和==区别</li>
<li>List 和 Set 区别</li>
<li>Java实现线程几种方式</li>
<li>Redis说一下，几种数据结构常用api</li>
<li>spring、springmvc、springboot、springcloud区别</li>
<li>springboot常用注解</li>
<li>AOP说一下</li>
<li>nacos，gateway，openFeign说一下(gateway原理</li>
<li>rabbitmg原理说一下，用来干嘛了</li>
<li>nginx说一下</li>
<li>linux部署、常用命令</li>
<li>反问</li>
</ol>
<h2 id="上海卓临" tabindex="-1"><a class="header-anchor" href="#上海卓临" aria-hidden="true">#</a> 上海卓临</h2>
<ol>
<li>自我介绍</li>
<li>项目背景（为什么会想做这个项目）</li>
<li>JVM运行流程</li>
<li>Java两大容器了解吗（Collection和Map）</li>
<li>你学的框架之间有什么区别？</li>
<li>了解过SVN吗？</li>
<li>Linux的常用命令</li>
<li>内连接和外连接有什么区别？</li>
<li>Redis了解多少？</li>
<li>一条SQL语句的执行过程</li>
<li>抽象类和普通类有什么区别？</li>
<li>线程和进程的区别？</li>
<li>有了进程为什么还要有线程？</li>
</ol>
<h2 id="谷川联行一面-说是过了一面之后会有二面" tabindex="-1"><a class="header-anchor" href="#谷川联行一面-说是过了一面之后会有二面" aria-hidden="true">#</a> 谷川联行一面（说是过了一面之后会有二面）</h2>
<ol>
<li>自我介绍</li>
<li>MySQL
<ul>
<li>索引在项目中有用到过吗？说一说你对索引的了解，再结合你之前的使用场景说一下你遇到了什么问题 ？为什么要用索引？解决了什么问题？</li>
<li>索引有哪些类型？你用到的是哪种？</li>
<li>QL优化，你有用过吗？</li>
<li>什么是回表查询？</li>
<li>你的项目用到过锁吗？说说你的了解</li>
<li>MySQL的隔离级别了解吗？提升隔离级别需要注意什么？为什么提升隔离级别性能会降低？</li>
<li>幻读和脏读的区别是什么？</li>
<li>解释一下mvcc？你觉得你的项目有哪个点可以用到？</li>
</ul>
</li>
<li>Redis
<ul>
<li>Redis都有哪些数据类型？你项目中用到了哪种？</li>
<li>你项目中用Redis做缓存是基于什么考量呢？</li>
<li>缓存穿透和雪崩的区别是什么？怎么避免缓存雪崩？</li>
</ul>
</li>
<li>RabbitMQ
<ul>
<li>用过RabbitMQ吗？说说你对RabbitMQ的了解</li>
<li>RabbitMQ的工作机制了解吗？</li>
</ul>
</li>
<li>数据结构
<ul>
<li>说一下链表，数组，B树，B+树</li>
<li>B+树的局限性</li>
</ul>
</li>
<li>设计模式
<ul>
<li>为什么要用设计模式？</li>
</ul>
</li>
<li>JVM
<ul>
<li>JVM垃圾回收机制了解吗？</li>
<li>JVM垃圾回收算法有哪些？详细说一下</li>
</ul>
</li>
<li>项目负责哪部分？对前端一些技术了解多少？VUE了解过吗？</li>
<li>面试官简单介绍了一下公司信息（业务和技术栈），然后问我还有什么想了解的</li>
</ol>
<h2 id="货拉拉的测开" tabindex="-1"><a class="header-anchor" href="#货拉拉的测开" aria-hidden="true">#</a> 货拉拉的测开</h2>
<p>面试官很好 他自己还开视频了 不会的就不深问 会的就循序渐进的问 不会的还教你 前面的有几个忘记录音了</p>
<ol>
<li>AOP的实现方式</li>
<li>有了解过用Java Agent实现AOP嘛</li>
<li>用AOP来干嘛</li>
<li>IO的方式有哪些</li>
<li>常用的设计模式有哪些</li>
<li>为什么要设计成单例</li>
<li>单例的线程安全问题</li>
<li>在什么样的数据结构要用到链表</li>
<li>java中哪些实现用到了链表</li>
<li>两个有序链表合并成一个有序链表</li>
<li>用什么方式实现多线程</li>
<li>拒绝策略有哪些</li>
<li>线程安全的list和map</li>
<li>说说concurrentHashMap</li>
<li>java的双亲委派</li>
<li>打破双亲委派的方式</li>
<li>java的SPI</li>
<li>用过哪些分布式应用</li>
<li>分布式锁的使用场景</li>
<li>ThreadLocal怎么保证集群下的数据一致性</li>
<li>为什么要用消息队列做异步处理</li>
<li>如何保证消息队列被全部消费</li>
<li>ThreadLocal多线程之间传递</li>
<li>了解一些测试工具嘛</li>
<li>问我base意向</li>
</ol>
<h2 id="连连支付" tabindex="-1"><a class="header-anchor" href="#连连支付" aria-hidden="true">#</a> 连连支付</h2>
<ol>
<li>讲一下项目</li>
<li>讲下redis的缓存穿透击穿雪崩</li>
<li>redis为什么快?</li>
<li>dubbo框架有了解过吗?</li>
<li>dubbo基础环境搭建具体怎么做?</li>
<li>注册中心如果挂了如何应对?</li>
<li>数据库用的啥?为啥选择MySQL?大致讲一下你对MSOL的理解</li>
<li>事务隔离级别?默认是哪种?</li>
<li>MySOL索引有了解过吗?</li>
<li>索引的原理大致有了解吗</li>
<li>讲下MySOL主从复制</li>
<li>mybatis了解过多少</li>
<li>gateway网关路由控制，请求分发具体怎么实现</li>
<li>讲一下责任链模式</li>
<li>spring核心模块</li>
<li>spring事务有了解吗</li>
<li>spring事务有哪几种传播级别</li>
<li>讲下ioc</li>
<li>创建bean的机制</li>
<li>讲一下aop</li>
<li>aop缺点，具体应用</li>
<li>vue熟悉吗</li>
<li>如果让你去写一个类似淘宝的电商项目你会怎么做讲一下你的思路</li>
<li>定时任务怎么实现</li>
<li>分布式锁具体讲一下</li>
<li>讲下sql优化</li>
<li>sentinel怎么实现流量控制</li>
</ol>
<h2 id="云徙科技" tabindex="-1"><a class="header-anchor" href="#云徙科技" aria-hidden="true">#</a> 云徙科技</h2>
<ol>
<li>mysql执行流程</li>
<li>怎么利用索引提高查询效率</li>
<li>mysql 事务是什么实现的</li>
<li>说说你对spring的了解</li>
<li>代理模式有什么好处</li>
<li>调用wait方法会怎么样</li>
<li>notify和allnotify的区别</li>
<li>说说你使用过的juc包下的类</li>
<li>说一下jvm垃圾回收</li>
<li>说说tcp和udp的区别</li>
<li>平常怎么学习?</li>
</ol>
<h2 id="恒生电子" tabindex="-1"><a class="header-anchor" href="#恒生电子" aria-hidden="true">#</a> 恒生电子</h2>
<ol>
<li>自我介绍</li>
<li>平时的一个学习状态（先闲聊）</li>
<li>针对展开项目讲讲（设计遇到的一些印象深的地方)</li>
<li>项目文档与代码的设计有什么想法（谈到时间安排上）</li>
<li>针对加班的看法 （接受就是）</li>
<li>集合的理解</li>
<li>多线程（实现，线程池）</li>
<li>谈谈浅拷贝和深拷贝？</li>
<li>mysq1索引</li>
<li>谈谈数据库设计表使用主键自增，不让主键自增？</li>
<li>redis的持久化机制</li>
<li>简单讲讲redis高可用</li>
</ol>
</div></template>


