export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-0cee75fa","/algorithm.html",{"y":"a","t":"algorithm"},[":md"]],
  ["v-a4e563c0","/docker.html",{"y":"a","t":"Docker"},[":md"]],
  ["v-4e9cb81e","/linux.html",{"y":"a","t":"Linux"},[":md"]],
  ["v-b30035a0","/mysql.html",{"y":"a","t":"MySQL"},[":md"]],
  ["v-1fe058e4","/network.html",{"y":"a","t":"计算机网络"},[":md"]],
  ["v-20cfb45c","/os.html",{"y":"a","t":"OS"},[":md"]],
  ["v-3ac5ce46","/projects.html",{"y":"a","t":"项目"},[":md"]],
  ["v-2524dff7","/redis.html",{"y":"a","t":"Redis"},[":md"]],
  ["v-296b7d84","/skills.html",{"y":"a","t":"专业技能","O":2},[":md"]],
  ["v-ab0c34e0","/framework/mybatis.html",{"y":"a","t":"MyBatis","O":3},[":md"]],
  ["v-910cd9fc","/framework/spring.html",{"y":"a","t":"Spring","O":1},[":md"]],
  ["v-5fdd22d0","/framework/springboot.html",{"y":"a","t":"Spring Boot","O":2},[":md"]],
  ["v-8de5d8fa","/java/java.html",{"y":"a","t":"Java 基础","O":1},[":md"]],
  ["v-46e51655","/java/juc.html",{"y":"a","t":"Java 并发编程","O":3},[":md"]],
  ["v-e6487068","/java/jvm.html",{"y":"a","t":"JVM","O":2},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-7d72c4ac","/framework/",{"y":"p","t":"Framework"},[]],
  ["v-14c69af4","/java/",{"y":"p","t":"Java"},[]],
  ["v-3200da36","/questions.html",{"y":"a","t":"题目"},[":md"]],
]
