export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-a4e563c0","/docker.html",{"y":"a","t":"Docker"},[":md"]],
  ["v-4e9cb81e","/linux.html",{"y":"a","t":"Linux"},[":md"]],
  ["v-b30035a0","/mysql.html",{"y":"a","t":"MySQL"},[":md"]],
  ["v-3ac5ce46","/projects.html",{"y":"a","t":"项目"},[":md"]],
  ["v-3200da36","/questions.html",{"y":"a","t":"题目"},[":md"]],
  ["v-2524dff7","/redis.html",{"y":"a","t":"Redis"},[":md"]],
  ["v-296b7d84","/skills.html",{"y":"a","t":"专业技能","O":2},[":md"]],
  ["v-d6577c66","/foundation/algorithm.html",{"y":"a","t":"算法","i":"tabler:math","O":2},[":md"]],
  ["v-783a4ff3","/foundation/datastructure.html",{"y":"a","t":"数据结构","i":"solar:structure-bold","O":1},[":md"]],
  ["v-3510ddac","/foundation/dp.html",{"y":"a","t":"设计模式","i":"icon-park:graphic-design","O":5},[":md"]],
  ["v-0898802e","/foundation/network.html",{"y":"a","t":"计算机网络","i":"fluent-mdl2:my-network","O":3},[":md"]],
  ["v-307aa6d2","/foundation/os.html",{"y":"a","t":"操作系统","i":"wpf:mac-os","O":4},[":md"]],
  ["v-f09009a2","/foundation/software.html",{"y":"a","t":"软件工程","i":"flat-color-icons:engineering","O":6},[":md"]],
  ["v-ab0c34e0","/framework/mybatis.html",{"y":"a","t":"MyBatis","i":"healthicons:3-outline","O":3},[":md"]],
  ["v-910cd9fc","/framework/spring.html",{"y":"a","t":"Spring","i":"healthicons:1-outline","O":1},[":md"]],
  ["v-5fdd22d0","/framework/springboot.html",{"y":"a","t":"Spring Boot","i":"healthicons:2-outline","O":2},[":md"]],
  ["v-61189b3b","/framework/springcloud.html",{"y":"a","t":"Spring Cloud","i":"healthicons:4-outline","O":4},[":md"]],
  ["v-8de5d8fa","/java/java.html",{"y":"a","t":"Java 基础","i":"healthicons:1-outline","O":1},[":md"]],
  ["v-46e51655","/java/juc.html",{"y":"a","t":"Java 并发编程","i":"healthicons:3-outline","O":3},[":md"]],
  ["v-e6487068","/java/jvm.html",{"y":"a","t":"JVM","i":"healthicons:2-outline","O":2},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-2dbc3943","/foundation/",{"y":"p","t":"Foundation"},[]],
  ["v-7d72c4ac","/framework/",{"y":"p","t":"Framework"},[]],
  ["v-14c69af4","/java/",{"y":"p","t":"Java"},[]],
]
