export const data = JSON.parse("{\"key\":\"v-243b3c9e\",\"path\":\"/java/java~.html\",\"title\":\"Java 基础\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":1,\"description\":\"String、StringBuffer、StringBuilder 的区别？ 1. 可变性 1. String 不可变、后两者可变 2. 线程安全 1. String, StringBuffer 线程安全 3. 性能 1. String 每次要 new 对象，性能低。 2. StringBuffer 可变但是线程安全，略微提升。 3. StringBu...\"},\"headers\":[{\"level\":2,\"title\":\"String、StringBuffer、StringBuilder 的区别？\",\"slug\":\"string、stringbuffer、stringbuilder-的区别\",\"link\":\"#string、stringbuffer、stringbuilder-的区别\",\"children\":[]},{\"level\":2,\"title\":\"String 为什么是不可变的？\",\"slug\":\"string-为什么是不可变的\",\"link\":\"#string-为什么是不可变的\",\"children\":[]},{\"level\":2,\"title\":\"Java 9 为何要将 String 的底层实现由 char[] 改成了 byte[] ?\",\"slug\":\"java-9-为何要将-string-的底层实现由-char-改成了-byte\",\"link\":\"#java-9-为何要将-string-的底层实现由-char-改成了-byte\",\"children\":[]},{\"level\":2,\"title\":\"String s1 = new String(\\\"abc\\\"); 这段代码创建了几个字符串对象？\",\"slug\":\"string-s1-new-string-abc-这段代码创建了几个字符串对象\",\"link\":\"#string-s1-new-string-abc-这段代码创建了几个字符串对象\",\"children\":[]},{\"level\":2,\"title\":\"== 和 equals() 的区别\",\"slug\":\"和-equals-的区别\",\"link\":\"#和-equals-的区别\",\"children\":[]},{\"level\":2,\"title\":\"hashCode() 作用\",\"slug\":\"hashcode-作用\",\"link\":\"#hashcode-作用\",\"children\":[]},{\"level\":2,\"title\":\"为什么重写 equals() 时必须重写 hashCode() 方法？\",\"slug\":\"为什么重写-equals-时必须重写-hashcode-方法\",\"link\":\"#为什么重写-equals-时必须重写-hashcode-方法\",\"children\":[]},{\"level\":2,\"title\":\"包装类型的缓存机制了解么？\",\"slug\":\"包装类型的缓存机制了解么\",\"link\":\"#包装类型的缓存机制了解么\",\"children\":[]},{\"level\":2,\"title\":\"自动装箱与拆箱了解吗？原理是什么？\",\"slug\":\"自动装箱与拆箱了解吗-原理是什么\",\"link\":\"#自动装箱与拆箱了解吗-原理是什么\",\"children\":[]},{\"level\":2,\"title\":\"注解\",\"slug\":\"注解\",\"link\":\"#注解\",\"children\":[]},{\"level\":2,\"title\":\"异常\",\"slug\":\"异常\",\"link\":\"#异常\",\"children\":[{\"level\":3,\"title\":\"Exception 和 Error 有什么区别？\",\"slug\":\"exception-和-error-有什么区别\",\"link\":\"#exception-和-error-有什么区别\",\"children\":[]}]},{\"level\":2,\"title\":\"重写和重载区别\",\"slug\":\"重写和重载区别\",\"link\":\"#重写和重载区别\",\"children\":[]},{\"level\":2,\"title\":\"集合\",\"slug\":\"集合\",\"link\":\"#集合\",\"children\":[{\"level\":3,\"title\":\"ArrayList 和 LinkedList 的区别?\",\"slug\":\"arraylist-和-linkedlist-的区别\",\"link\":\"#arraylist-和-linkedlist-的区别\",\"children\":[]}]},{\"level\":2,\"title\":\"面向对象\",\"slug\":\"面向对象\",\"link\":\"#面向对象\",\"children\":[{\"level\":3,\"title\":\"三大特征\",\"slug\":\"三大特征\",\"link\":\"#三大特征\",\"children\":[]},{\"level\":3,\"title\":\"深拷贝和浅拷贝区别了解吗？什么是引用拷贝？\",\"slug\":\"深拷贝和浅拷贝区别了解吗-什么是引用拷贝\",\"link\":\"#深拷贝和浅拷贝区别了解吗-什么是引用拷贝\",\"children\":[]}]}],\"readingTime\":{\"minutes\":5.69,\"words\":1707},\"filePathRelative\":\"java/java~.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
