export const data = JSON.parse("{\"key\":\"v-e6487068\",\"path\":\"/java/jvm.html\",\"title\":\"JVM\",\"lang\":\"zh-CN\",\"frontmatter\":{\"order\":2,\"description\":\"JVM 架构 1. 类加载器 1. 加载 1. 双亲委派 2. 链接 1. 验证 2. 准备 3. 解析 3. 初始化 2. 运行时数据区域 3. 执行引擎 1. 解释器 1. 读取 class 文件或者字节码并执行。 2. 缺点：如果一个方法被多次调用，代码会被它多次编译 2. JIT 编译器 1. 解决了解释器的问题 2. 如果出现了重复调用，JI...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/java-interview/java/jvm.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"后端面试经验\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"JVM\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"JVM 架构 1. 类加载器 1. 加载 1. 双亲委派 2. 链接 1. 验证 2. 准备 3. 解析 3. 初始化 2. 运行时数据区域 3. 执行引擎 1. 解释器 1. 读取 class 文件或者字节码并执行。 2. 缺点：如果一个方法被多次调用，代码会被它多次编译 2. JIT 编译器 1. 解决了解释器的问题 2. 如果出现了重复调用，JI...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"Ding\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"JVM\\\",\\\"image\\\":[\\\"\\\"],\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"Ding\\\",\\\"url\\\":\\\"https://github.com/prgding\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"JVM 架构\",\"slug\":\"jvm-架构\",\"link\":\"#jvm-架构\",\"children\":[]},{\"level\":2,\"title\":\"JVM 运行流程\",\"slug\":\"jvm-运行流程\",\"link\":\"#jvm-运行流程\",\"children\":[]},{\"level\":2,\"title\":\"运行时数据区域\",\"slug\":\"运行时数据区域\",\"link\":\"#运行时数据区域\",\"children\":[]},{\"level\":2,\"title\":\"垃圾回收机制\",\"slug\":\"垃圾回收机制\",\"link\":\"#垃圾回收机制\",\"children\":[{\"level\":3,\"title\":\"对象什么时候被回收\",\"slug\":\"对象什么时候被回收\",\"link\":\"#对象什么时候被回收\",\"children\":[]},{\"level\":3,\"title\":\"垃圾回收算法\",\"slug\":\"垃圾回收算法\",\"link\":\"#垃圾回收算法\",\"children\":[]}]},{\"level\":2,\"title\":\"双亲委派机制\",\"slug\":\"双亲委派机制\",\"link\":\"#双亲委派机制\",\"children\":[{\"level\":3,\"title\":\"是什么\",\"slug\":\"是什么\",\"link\":\"#是什么\",\"children\":[]},{\"level\":3,\"title\":\"为什么使用双亲委派？\",\"slug\":\"为什么使用双亲委派\",\"link\":\"#为什么使用双亲委派\",\"children\":[]},{\"level\":3,\"title\":\"打破双亲委派机制\",\"slug\":\"打破双亲委派机制\",\"link\":\"#打破双亲委派机制\",\"children\":[]},{\"level\":3,\"title\":\"注意事项\",\"slug\":\"注意事项\",\"link\":\"#注意事项\",\"children\":[]}]}],\"readingTime\":{\"minutes\":4.19,\"words\":1258},\"filePathRelative\":\"java/jvm.md\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
