name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: prgding/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.SECRET }}
        TARGET_REPO: prgding/java-interview
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn && yarn docs:build
        BUILD_DIR: src/.vuepress/dist/
